# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'davaleba.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_MainWindow(object):
    def setupUi(self, Ui_MainWindow):
        Ui_MainWindow.setObjectName("Ui_MainWindow")
        Ui_MainWindow.resize(2188, 1027)
        Ui_MainWindow.setStyleSheet("background-color: blue\n"
"")
        self.centralwidget = QtWidgets.QWidget(Ui_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(720, 440, 521, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.submit.setFont(font)
        self.submit.setStyleSheet("background-color: cyan\n"
"")
        self.submit.setObjectName("submit")
        self.game_title = QtWidgets.QLabel(self.centralwidget)
        self.game_title.setGeometry(QtCore.QRect(720, 100, 521, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.game_title.setFont(font)
        self.game_title.setStyleSheet("background-color: cyan")
        self.game_title.setObjectName("game_title")
        self.restart = QtWidgets.QPushButton(self.centralwidget)
        self.restart.setGeometry(QtCore.QRect(720, 640, 521, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.restart.setFont(font)
        self.restart.setStyleSheet("background-color: cyan\n"
"")
        self.restart.setObjectName("restart")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(720, 810, 521, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.exit.setFont(font)
        self.exit.setStyleSheet("background-color: cyan\n"
"")
        self.exit.setObjectName("exit")
        self.button_guess_the_number = QtWidgets.QLineEdit(self.centralwidget)
        self.button_guess_the_number.setGeometry(QtCore.QRect(720, 260, 521, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.button_guess_the_number.setFont(font)
        self.button_guess_the_number.setStyleSheet("background-color: white\n"
"")
        self.button_guess_the_number.setText("")
        self.button_guess_the_number.setObjectName("button_guess_the_number")
        self.mute = QtWidgets.QRadioButton(self.centralwidget)
        self.mute.setGeometry(QtCore.QRect(30, 860, 191, 41))
        self.mute.setStyleSheet("color: white")
        self.mute.setObjectName("mute")
        Ui_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ui_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2188, 25))
        self.menubar.setObjectName("menubar")
        Ui_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ui_MainWindow)
        self.statusbar.setObjectName("statusbar")
        Ui_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Ui_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Ui_MainWindow)

    def retranslateUi(self, Ui_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Ui_MainWindow.setWindowTitle(_translate("Ui_MainWindow", "MainWindow"))
        self.submit.setText(_translate("Ui_MainWindow", "submit"))
        self.game_title.setText(_translate("Ui_MainWindow", "                   guess the number game"))
        self.restart.setText(_translate("Ui_MainWindow", "restart"))
        self.exit.setText(_translate("Ui_MainWindow", "exit"))
        self.button_guess_the_number.setPlaceholderText(_translate("Ui_MainWindow", "enter a num(1-10): "))
        self.mute.setText(_translate("Ui_MainWindow", "mute"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Ui_MainWindow()
    ui.setupUi(Ui_MainWindow)
    Ui_MainWindow.show()
    sys.exit(app.exec_())
